/*
 * Builds screen/ into actions/screen/assets.generated.js, which the `screen` action
 * serves. Runs as the pre-app-build hook, so every deploy ships the current screen.
 *
 * Refuses a file over Runtime's 1 MB result limit: the action would deploy and
 * then fail every request for that file.
 */
const path = require('path')
const fs = require('fs')
const esbuild = require('esbuild')

const ROOT = path.join(__dirname, '..')
const OUT = path.join(ROOT, 'actions', 'screen', 'assets.generated.js')
const RESULT_LIMIT_BYTES = 1024 * 1024
// A response also carries headers and a JSON envelope; keep clear of the edge.
const BUDGET_BYTES = Math.floor(RESULT_LIMIT_BYTES * 0.95)

async function build () {
  const result = await esbuild.build({
    entryPoints: [path.join(ROOT, 'screen', 'src', 'index.js')],
    bundle: true,
    minify: true,
    format: 'esm',
    write: false,
    outdir: 'out',
    loader: { '.js': 'jsx' },
    jsx: 'automatic',
    define: { 'process.env.NODE_ENV': '"production"' },
    logLevel: 'warning'
  })
  const files = Object.fromEntries(result.outputFiles.map((f) => [path.extname(f.path).slice(1), f.text]))
  for (const kind of ['js', 'css']) {
    if (typeof files[kind] !== 'string') throw new Error(`The screen build produced no ${kind} file.`)
    const size = Buffer.byteLength(files[kind])
    if (size > BUDGET_BYTES) {
      throw new Error(`The screen's ${kind} is ${size} bytes; Runtime answers at most ${RESULT_LIMIT_BYTES}. Split it before deploying.`)
    }
  }
  fs.writeFileSync(OUT, `// Generated by scripts/build-screen.js. Do not edit.\nmodule.exports = ${JSON.stringify({ js: files.js, css: files.css })}\n`)
  console.log(`screen built: js ${Buffer.byteLength(files.js)} bytes, css ${Buffer.byteLength(files.css)} bytes`)
}

build().catch((error) => {
  console.error(error.message)
  process.exit(1)
})
